# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='site_access_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
