# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0008_auto_20160808_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 11, 22, 16, 516000)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 11, 22, 16, 515000)),
        ),
    ]
