# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0009_auto_20160808_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 11, 24, 9, 131000)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 8, 11, 24, 9, 130000)),
        ),
    ]
